DROP TABLE IF EXISTS "user_person" CASCADE;
DROP TABLE IF EXISTS "hardware" CASCADE;
DROP TABLE IF EXISTS "node" CASCADE;
DROP TABLE IF EXISTS "sensor" CASCADE;
DROP TABLE IF EXISTS "channel" CASCADE;
