insert into hardware (name, type, description) values ('Hegmann and Sons', 'microcontroller unit', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into hardware (name, type, description) values ('Hartmann, Ziemann and Weber', 'single-board computer', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into hardware (name, type, description) values ('Jenkins-Cole', 'sensor', 'In congue.');
insert into hardware (name, type, description) values ('Swift, Cummerata and Parker', 'sensor', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into hardware (name, type, description) values ('Kulas, Zulauf and Doyle', 'sensor', 'Nulla nisl.');
insert into hardware (name, type, description) values ('Schmidt, Stokes and Wintheiser', 'single-board computer', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into hardware (name, type, description) values ('Hodkiewicz Group', 'sensor', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into hardware (name, type, description) values ('Reichel, Anderson and McCullough', 'sensor', 'Maecenas rhoncus aliquam lacus.');
insert into hardware (name, type, description) values ('Littel, Littel and Thompson', 'single-board computer', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into hardware (name, type, description) values ('Borer, Mohr and Renner', 'microcontroller unit', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into hardware (name, type, description) values ('Lindgren, Terry and Huels', 'single-board computer', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into hardware (name, type, description) values ('Leffler Inc', 'microcontroller unit', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into hardware (name, type, description) values ('Kris-Bins', 'microcontroller unit', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into hardware (name, type, description) values ('Ferry, Casper and Rogahn', 'sensor', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into hardware (name, type, description) values ('Crooks and Sons', 'sensor', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into hardware (name, type, description) values ('McClure, Gutkowski and Wyman', 'microcontroller unit', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into hardware (name, type, description) values ('VonRueden LLC', 'sensor', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into hardware (name, type, description) values ('Schuppe-Corwin', 'single-board computer', 'Nulla tellus. In sagittis dui vel nisl.');
insert into hardware (name, type, description) values ('Ryan, Anderson and Gusikowski', 'microcontroller unit', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.');
insert into hardware (name, type, description) values ('Jakubowski, Lowe and Johnson', 'sensor', 'Nulla ac enim.');
