insert into node (name, location, id_user, id_hardware) values ('Rosenbaum-Breitenberg', 'Maple Wood', 1, 4);
insert into node (name, location, id_user, id_hardware) values ('Schimmel-Mosciski', 'Becker', 2, 18);
insert into node (name, location, id_user, id_hardware) values ('Nolan, Hilpert and Pagac', 'Arkansas', 1, 5);
insert into node (name, location, id_user, id_hardware) values ('Lueilwitz, Schroeder and Hahn', 'Prentice', 2, 6);
insert into node (name, location, id_user, id_hardware) values ('Stokes Inc', 'Evergreen', 2, 17);
insert into node (name, location, id_user, id_hardware) values ('Lind-Will', 'North', 2, 20);
insert into node (name, location, id_user, id_hardware) values ('O''Conner-Simonis', 'Sycamore', 1, 17);
insert into node (name, location, id_user, id_hardware) values ('Cole-Hermann', 'Dovetail', 2, 19);
insert into node (name, location, id_user, id_hardware) values ('Ratke-Hansen', 'Mitchell', 2, 14);
insert into node (name, location, id_user, id_hardware) values ('Lockman-Olson', 'Miller', 2, 2);
insert into node (name, location, id_user, id_hardware) values ('Collins-Cassin', 'Hayes', 1, 6);
insert into node (name, location, id_user, id_hardware) values ('Jast-Abshire', 'Fulton', 2, 19);
insert into node (name, location, id_user, id_hardware) values ('Simonis LLC', 'Farmco', 1, 2);
insert into node (name, location, id_user, id_hardware) values ('Vandervort, Harvey and Gibson', 'Gale', 2, 11);
insert into node (name, location, id_user, id_hardware) values ('Heidenreich and Sons', 'Holy Cross', 2, 10);
insert into node (name, location, id_user, id_hardware) values ('Lockman Inc', 'Meadow Ridge', 2, 1);
insert into node (name, location, id_user, id_hardware) values ('Gottlieb, Conroy and Quigley', 'Fuller', 1, 11);
insert into node (name, location, id_user, id_hardware) values ('Johnson Group', 'Hoard', 1, 18);
insert into node (name, location, id_user, id_hardware) values ('Schuster-Effertz', 'Fair Oaks', 1, 3);
insert into node (name, location, id_user, id_hardware) values ('Yost LLC', 'Dixon', 1, 2);
insert into node (name, location, id_user, id_hardware) values ('Cruickshank-Rodriguez', 'Blackbird', 2, 17);
insert into node (name, location, id_user, id_hardware) values ('Breitenberg-Kessler', 'Doe Crossing', 1, 5);
insert into node (name, location, id_user, id_hardware) values ('Legros-O''Reilly', 'Glacier Hill', 2, 16);
insert into node (name, location, id_user, id_hardware) values ('Wisozk, Hickle and Hahn', 'Dennis', 1, 12);
insert into node (name, location, id_user, id_hardware) values ('Hamill, Bartell and Erdman', 'Laurel', 1, 19);
insert into node (name, location, id_user, id_hardware) values ('Upton Inc', 'Kenwood', 1, 6);
insert into node (name, location, id_user, id_hardware) values ('Barton, Ortiz and Dickens', 'Toban', 1, 15);
insert into node (name, location, id_user, id_hardware) values ('Baumbach-Kreiger', 'Crescent Oaks', 2, 10);
insert into node (name, location, id_user, id_hardware) values ('Stehr-Ziemann', 'Moulton', 2, 2);
insert into node (name, location, id_user, id_hardware) values ('Kunze-Corkery', 'Meadow Valley', 2, 5);
