insert into sensor (name, unit, id_node, id_hardware) values ('Rodriguez-Block', 'context-sensitive', 18, 17);
insert into sensor (name, unit, id_node, id_hardware) values ('Rodriguez-Hoppe', 'project', 3, 20);
insert into sensor (name, unit, id_node, id_hardware) values ('Wehner-Gibson', 'project', 2, 8);
insert into sensor (name, unit, id_node, id_hardware) values ('Borer and Sons', 'user-facing', 26, 10);
insert into sensor (name, unit, id_node, id_hardware) values ('Tremblay and Sons', 'frame', 14, 2);
insert into sensor (name, unit, id_node, id_hardware) values ('Pollich-Anderson', 'Managed', 11, 12);
insert into sensor (name, unit, id_node, id_hardware) values ('Heathcote-Rempel', 'concept', 21, 5);
insert into sensor (name, unit, id_node, id_hardware) values ('Bernier-Denesik', 'Function-based', 11, 12);
insert into sensor (name, unit, id_node, id_hardware) values ('Mraz, Glover and Gleason', 'stable', 22, 11);
insert into sensor (name, unit, id_node, id_hardware) values ('Crona, Baumbach and Huel', 'Intuitive', 25, 1);
insert into sensor (name, unit, id_node, id_hardware) values ('Powlowski-Considine', 'Quality-focused', 30, 2);
insert into sensor (name, unit, id_node, id_hardware) values ('Jast, Hyatt and Bogisich', 'Expanded', 30, 18);
insert into sensor (name, unit, id_node, id_hardware) values ('Hegmann-Padberg', 'methodology', 3, 5);
insert into sensor (name, unit, id_node, id_hardware) values ('Prosacco, Keebler and Stanton', 'multi-state', 19, 12);
insert into sensor (name, unit, id_node, id_hardware) values ('Mueller, Schneider and Hane', 'Distributed', 1, 17);
insert into sensor (name, unit, id_node, id_hardware) values ('Goldner-Medhurst', 'ability', 11, 5);
insert into sensor (name, unit, id_node, id_hardware) values ('Daugherty, Schmeler and Kessler', 'Programmable', 27, 13);
insert into sensor (name, unit, id_node, id_hardware) values ('Powlowski, Kshlerin and Orn', 'Vision-oriented', 23, 1);
insert into sensor (name, unit, id_node, id_hardware) values ('Weber Inc', 'alliance', 11, 15);
insert into sensor (name, unit, id_node, id_hardware) values ('Ziemann, Barton and Toy', 'Front-line', 21, 1);
insert into sensor (name, unit, id_node, id_hardware) values ('Towne-Windler', 'policy', 15, 19);
insert into sensor (name, unit, id_node, id_hardware) values ('Mraz-Ullrich', 'Up-sized', 29, 7);
insert into sensor (name, unit, id_node, id_hardware) values ('Bashirian LLC', 'service-desk', 9, 5);
insert into sensor (name, unit, id_node, id_hardware) values ('Price and Sons', 'Virtual', 22, 17);
insert into sensor (name, unit, id_node, id_hardware) values ('Kuhic and Sons', 'empowering', 26, 3);
insert into sensor (name, unit, id_node, id_hardware) values ('Emmerich Group', 'capacity', 25, 14);
insert into sensor (name, unit, id_node, id_hardware) values ('Conn-Reinger', 'real-time', 2, 11);
insert into sensor (name, unit, id_node, id_hardware) values ('Pouros-Breitenberg', 'composite', 27, 12);
insert into sensor (name, unit, id_node, id_hardware) values ('Halvorson and Sons', 'fault-tolerant', 20, 6);
insert into sensor (name, unit, id_node, id_hardware) values ('Kuhn and Sons', 'workforce', 10, 1);
insert into sensor (name, unit, id_node, id_hardware) values ('Johnston Inc', 'Triple-buffered', 3, 5);
insert into sensor (name, unit, id_node, id_hardware) values ('Koch, Schinner and Leannon', 'Face to face', 4, 17);
insert into sensor (name, unit, id_node, id_hardware) values ('Waelchi LLC', 'encoding', 5, 6);
insert into sensor (name, unit, id_node, id_hardware) values ('Gaylord-Wehner', 'value-added', 30, 4);
insert into sensor (name, unit, id_node, id_hardware) values ('Corwin, Walsh and Bayer', 'content-based', 10, 2);
insert into sensor (name, unit, id_node, id_hardware) values ('Lakin-Yost', 'encompassing', 18, 10);
insert into sensor (name, unit, id_node, id_hardware) values ('Reilly-Osinski', 'disintermediate', 3, 9);
insert into sensor (name, unit, id_node, id_hardware) values ('Howe, Miller and DuBuque', 'artificial intelligence', 1, 7);
insert into sensor (name, unit, id_node, id_hardware) values ('Prohaska, Ratke and Hessel', 'ability', 17, 12);
insert into sensor (name, unit, id_node, id_hardware) values ('Parker-Hayes', 'Reactive', 25, 10);
insert into sensor (name, unit, id_node, id_hardware) values ('McCullough-Schulist', 'portal', 28, 15);
insert into sensor (name, unit, id_node, id_hardware) values ('Hilpert-Hodkiewicz', 'non-volatile', 9, 6);
insert into sensor (name, unit, id_node, id_hardware) values ('Marks Group', 'Polarised', 17, 17);
insert into sensor (name, unit, id_node, id_hardware) values ('Kertzmann LLC', 'toolset', 26, 2);
insert into sensor (name, unit, id_node, id_hardware) values ('Moore-Gleichner', 'executive', 26, 14);
insert into sensor (name, unit, id_node, id_hardware) values ('Gulgowski-Gulgowski', 'Organized', 7, 8);
insert into sensor (name, unit, id_node, id_hardware) values ('Kemmer and Sons', 'projection', 27, 9);
insert into sensor (name, unit, id_node, id_hardware) values ('Ferry-Block', 'time-frame', 7, 1);
insert into sensor (name, unit, id_node, id_hardware) values ('Cassin, Medhurst and Zemlak', 'real-time', 18, 14);
insert into sensor (name, unit, id_node, id_hardware) values ('Kuhn, Lakin and Wisoky', 'mission-critical', 25, 17);
