CREATE TABLE IF NOT EXISTS user_person (
  id_user SERIAL PRIMARY KEY, 
  username VARCHAR (255) NOT NULL UNIQUE, 
  email VARCHAR (255) NOT NULL UNIQUE, 
  password VARCHAR (255) NOT NULL, 
  status BOOLEAN DEFAULT FALSE, 
  isadmin BOOLEAN DEFAULT FALSE, 
  token VARCHAR (255)
);
CREATE TABLE IF NOT EXISTS hardware (
  id_hardware SERIAL PRIMARY KEY, 
  name VARCHAR (255) NOT NULL, 
  type VARCHAR (255) NOT NULL, 
  description VARCHAR (255) NOT NULL
);
CREATE TABLE IF NOT EXISTS node (
  id_node SERIAL PRIMARY KEY, 
  name VARCHAR (255) NOT NULL, 
  location VARCHAR (255) NOT NULL, 
  id_hardware INTEGER NOT NULL, 
  id_user INTEGER NOT NULL, 
  FOREIGN KEY (id_hardware) REFERENCES hardware (id_hardware) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY (id_user) REFERENCES user_person (id_user) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS sensor (
  id_sensor SERIAL PRIMARY KEY, 
  name VARCHAR (255) NOT NULL, 
  unit VARCHAR (255) NOT NULL, 
  id_hardware INTEGER NOT NULL, 
  id_node INTEGER NOT NULL, 
  FOREIGN KEY (id_hardware) REFERENCES hardware (id_hardware) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY (id_node) REFERENCES node (id_node) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS channel (
  time TIMESTAMP, 
  value FLOAT NOT NULL, 
  id_sensor INTEGER NOT NULL, 
  FOREIGN KEY (id_sensor) REFERENCES sensor (id_sensor) ON UPDATE CASCADE ON DELETE CASCADE
);
